version: "3.8"
services:
  app:
    build: .
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: pgpassword
      DB_NAME: postgres
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"

  postgres:
    image: postgres:14.1
    restart: always
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: postgres

